In [1]:
import numpy as np

In [2]:
X = np.array([[1, 5],[6, 2]])

In [3]:
w1 = np.array([[0.4, 0.2, 0.2, 0.4],
              [-0.5, -0.3, 0.3, 0.3],
              [0.5, -0.4, -0.2, 0.2]])

w2 = np.array([[0.5, 0, -0.1],
              [0, 0.4, -0.2],
              [0.5, -0.4, 0],
              [-0.4, 0.3, 0],
              [0, 0.2, 0.3]])

w3 = np.array([[0.1, -0.3, 0.1],
              [0.5, 0.1, -0.4],
              [0.4, 0, 0.2],
              [-0.3, 0.1, 0.5]])

In [4]:
# add a column of 1's for the biased term.
bias = np.array([[1],[1]])
X_biased = np.hstack((bias, X))
print(X_biased)

[[1 1 5]
 [1 6 2]]


In [5]:
# multiply the X_biased matrix with the w1 matrix.
z1 = np.dot(X_biased, w1)
print(z1)

[[ 2.4 -2.1 -0.5  1.7]
 [-1.6 -2.4  1.6  2.6]]


In [6]:
# relu function.
def ReLU(x):
    return abs(x * (x > 0))

In [7]:
# run the z1 matrix through the relu function.
a1 = ReLU(z1)
print(a1)

[[2.4 0.  0.  1.7]
 [0.  0.  1.6 2.6]]


In [8]:
# add a column of 1's for the biased term.
a1_biased = np.hstack((bias, a1))
print(a1_biased)

[[1.  2.4 0.  0.  1.7]
 [1.  0.  0.  1.6 2.6]]


In [9]:
# multiply the a1_biased matrix with the w2 matrix.
z2 = np.dot(a1_biased, w2)
print(z2)

[[ 0.5   1.3  -0.07]
 [-0.14  1.    0.68]]


In [10]:
# run the z2 matrix through the relu function.
a2 = ReLU(z2)
print(a2)

[[0.5  1.3  0.  ]
 [0.   1.   0.68]]


In [11]:
# add a column of 1's for the biased term.
a2_biased = np.hstack((bias, a2))
print(a2_biased)

[[1.   0.5  1.3  0.  ]
 [1.   0.   1.   0.68]]


In [12]:
# multiply the a2_biased matrix with the w3 matrix.
z3 = np.dot(a2_biased, w3)
print(z3)

[[ 0.87  -0.25   0.16 ]
 [ 0.296 -0.232  0.64 ]]


In [13]:
# find the e^z3 matrix.
e_z3 = np.exp(z3)
print(e_z3)

[[2.38691085 0.77880078 1.17351087]
 [1.34447016 0.79294612 1.89648088]]


In [14]:
# find the sum of the rows of e^z3.
rowSum = np.array([np.sum(e_z3, axis = 1)])
print(rowSum)

[[4.33922251 4.03389716]]


In [15]:
# softmax function.
def softmax(x):
    e_x = np.exp(x)
    sumOfRows = np.array([np.sum(e_x, axis = 1)])
    reshaped = np.reshape(sumOfRows, (2,1))
    return e_x / reshaped

In [16]:
# run the z3 matrix through the softmax function.
a3 = softmax(z3)
print(a3)

[[0.550078   0.17947934 0.27044266]
 [0.33329312 0.19657073 0.47013615]]
