## Homework 01

**David Clapp**

**DSCI 39001 - Neural Networks**

**Due Friday, Jan. 25, 9 AM**

This assignment is intended to give you practice working with NumPy arrays. The following resources are useful references for NumPy.
* [Python Data Science Handbook, Chapter 2](https://jakevdp.github.io/PythonDataScienceHandbook/)
* [DataCamp: Introduction to Python, Chapter 4](https://www.datacamp.com/courses/intro-to-python-for-data-science)

In the cell below, import NumPy under the alias `np`. 

In [1]:
import numpy as np

### Part A - Creating 2D Numpy Arrays

Create 2D NumPy arrays `A`, `B`, `C`, and `D` representing the matrices shown below. The following DataCamp video provides an example of how to do this: [2D NumPy Arrays](https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-4-numpy?ex=8).

$
A = \left[ {\begin{array}{cc} 3 & 9 & 8 & 7 \\ 6 & 8 & 2 & 1 \\ \end{array} } \right] \hspace{1cm}
B = \left[ {\begin{array}{cc} 8 & 3 & 9 \\ 8 & 5 & 5 \\ 7 & 4 & 1 \\ 3 & 4 & 5 \\ \end{array} } \right] \hspace{1cm}
C = \left[ {\begin{array}{cc} 5 & 3 & 7 \\ 9 & 3 & 1 \\ 8 & 5 & 2 \\ \end{array} } \right]
D = \left[ {\begin{array}{cc} 6 & 5 & 7 \\ 3 & 5 & 8 \\ \end{array} } \right] \hspace{1cm}
$

Print all four arrays. Display a blank line between the printout of each pair of arrays.

In [2]:
A = np.array([[3, 9, 8, 7], [6, 8, 2, 1]])
B = np.array([[8, 3, 9],[8, 5, 5],[7, 4, 1],[3, 4, 5]])
C = np.array([[5, 3, 7],[9, 3, 1],[8, 5, 2]])
D = np.array([[6, 5, 7],[3, 5, 8]])
print(A)
print()
print(B)
print()
print(C)
print()
print(D)

[[3 9 8 7]
 [6 8 2 1]]

[[8 3 9]
 [8 5 5]
 [7 4 1]
 [3 4 5]]

[[5 3 7]
 [9 3 1]
 [8 5 2]]

[[6 5 7]
 [3 5 8]]


### Part B: Array Concatenation

The `hstack` and `vstack` NumPy functions are useful for concatenating NumPy Arrays. You can see a short demonstration of the the usage of these functions in [this video](https://www.youtube.com/watch?v=ksqPbrS-b78). 

Stack the two arrays `A` and `D` side-by-side with `A` to the left of `D`, printing the result. You should get a NumPy array that represents the following matrix:

$\left[ {\begin{array}{cc} 3 & 9 & 8 & 7 & 6 & 5 & 7 \\ 6 & 8 & 2 & 1 & 3 & 5 & 8 \\ \end{array} } \right] $



In [3]:
np.hstack((A,D))

array([[3, 9, 8, 7, 6, 5, 7],
       [6, 8, 2, 1, 3, 5, 8]])

Stack the arrays `B`, `C`, and `D` vertically, in that order from top to bottom, printing the result. You should get a NumPy array that represents the following matrix:

$\left[ {\begin{array}{cc} 
8 & 3 & 9 \\ 8 & 5 & 5 \\ 7 & 4 & 1 \\ 3 & 4 & 5 \\ 5 & 3 & 7 \\ 9 & 3 & 1 \\ 8 & 5 & 2 \\ 6 & 5 & 7 \\ 3 & 5 & 8 \\ 
\end{array} } \right] $

In [4]:
np.vstack((B,C,D))

array([[8, 3, 9],
       [8, 5, 5],
       [7, 4, 1],
       [3, 4, 5],
       [5, 3, 7],
       [9, 3, 1],
       [8, 5, 2],
       [6, 5, 7],
       [3, 5, 8]])

### Part C: Matrix Multiplication

The default arithmetic operations on NumPy arrays perform element-wise operations. You can get the standard matrix product of two matrices represented by 2D arrays `P` and `Q` using `np.dot(P,Q)`. 

In Part A, we represented four different matrices with arrays. We could consider up to 16 possible matrix products of these matrices (assuming we consider the product of each matrix with itself). Some of these matrices will not be defined. 

In the cell below, calculate and print out the result of each matrix multiplication for which the product is actually defined. Immediately about each product, explain which matrices are being multiplied by printing a string with the following format: **`P x Q =`**. Use a new code cell for each matrix product. You can create a new cell by selecting a cell (clicking to the left of it) and typing `a` or `b`.

In [5]:
print('A x B = ', np.dot(A,B))

A x B =  [[173 114 115]
 [129  70 101]]


In [6]:
print('B x C = ', np.dot(B,C))

B x C =  [[139  78  77]
 [125  64  71]
 [ 79  38  55]
 [ 91  46  35]]


In [7]:
print('C x C = ', np.dot(C,C))

C x C =  [[108  59  52]
 [ 80  41  68]
 [101  49  65]]


In [8]:
print('D x C = ', np.dot(D,C))

D x C =  [[131  68  61]
 [124  64  42]]


### Part D: Array Shape

Every NumPy has a shape attribute that tells you the number of dimensions of the array, as well as the size of the array along each of its axis. The shape of an array can be accessed using `my_array.shape`. 

The cell below creates a randomly generated 2D array `W`. Add a line to this cell to print the shape of `W`. Your result will change every time you run this cell. 

In [9]:
size = np.random.choice(range(100), 2)
W = np.random.uniform(0, 1, size)
del size

print(W.shape)

(25, 19)


Four arrays are defined in the cell below. For each array, print the shape of the array, followed (on a seperate line) by the contents of that array. Use a different cell for each of the four arrays. 
     
Make sure you understand why each array has the shape that is reported. 

In [10]:
F1 = np.array([1, 2, 3, 4])
F2 = np.array([[1, 2, 3, 4]])
F3 = np.array([[1, 2], [3, 4]])
F4 = np.array([[1], [2], [3], [4]])

In [11]:
print(F1.shape)
print(F1)

(4,)
[1 2 3 4]


In [12]:
print(F2.shape)
print(F2)

(1, 4)
[[1 2 3 4]]


In [13]:
print(F3.shape)
print(F3)

(2, 2)
[[1 2]
 [3 4]]


In [14]:
print(F4.shape)
print(F4)

(4, 1)
[[1]
 [2]
 [3]
 [4]]


We can use the `reshape` function to generate a copy of an array with the same contents, but with a different shape. Some examples of `reshape` can be found on [this page](https://www.geeksforgeeks.org/numpy-reshape-python/). 

In the cell below, we create a 1D array with 24 randomly generated entries. In other words, this array has shape `(24,)`. Reshape this array in three different ways, printing the results each time. In particular:
* Reshape the array to one with 2 rows.
* Reshape the array to one with 3 rows.
* Reshape the array to one with 4 rows.

Print a blank link between each pair of arrays displayed. 

In [15]:
np.random.seed(1)
M = np.random.uniform(0, 4, 24)
M = np.round(M, 1)
print(M.reshape(2, 12))
print()
print(M.reshape(3, 8))
print()
print(M.reshape(4, 6))

[[1.7 2.9 0.  1.2 0.6 0.4 0.7 1.4 1.6 2.2 1.7 2.7]
 [0.8 3.5 0.1 2.7 1.7 2.2 0.6 0.8 3.2 3.9 1.3 2.8]]

[[1.7 2.9 0.  1.2 0.6 0.4 0.7 1.4]
 [1.6 2.2 1.7 2.7 0.8 3.5 0.1 2.7]
 [1.7 2.2 0.6 0.8 3.2 3.9 1.3 2.8]]

[[1.7 2.9 0.  1.2 0.6 0.4]
 [0.7 1.4 1.6 2.2 1.7 2.7]
 [0.8 3.5 0.1 2.7 1.7 2.2]
 [0.6 0.8 3.2 3.9 1.3 2.8]]


In the following cell, we create three randomly generated arrays: `P1` has shape `(15,)`, `P2` has shape `(18,)`, and `P3` has shape `(24,)`. There are also lines of code that are intended to calculate matrix products of reshaped versions of these arrays. Replace the blanks within the `reshape` functions so that the matrix products are defined. 

In [16]:
np.random.seed(1)

P1 = np.random.choice(range(10), 15)
P2 = np.random.choice(range(10), 18)
P3 = np.random.choice(range(10), 24)

print(np.dot(P1.reshape(5,3), P2.reshape(3,6)))
print()
print(np.dot(P2.reshape(3,6), P3.reshape(6,4)))
print()
print(np.dot(P3.reshape(8,3), P1.reshape(3,5)))


[[120 101  92 107 126 133]
 [ 10  20  35  35  45   5]
 [ 87  58  55  70  78  98]
 [ 56  72  79  81 103  55]
 [ 48  56  51  53  67  51]]

[[138 178 111  71]
 [189 228 149 129]
 [147 135 129 153]]

[[ 58 103 138  76  63]
 [ 46  83 136  88  75]
 [ 32  57  94  62  49]
 [ 53  91 122  71  43]
 [ 48  81  99  54  25]
 [ 18  39  66  36  63]
 [ 18  32  38  18  16]
 [ 59 102 130  71  46]]


### Part E: Array Sums

We can use the function `np.sum` to sum the contents of an array, or two sum an array along one of its axes. An explanation of this function (with examples) can be found here: [How to use the NumPy Sum Function](https://www.sharpsightlabs.com/blog/numpy-sum/).

In the cell below, we define a randomly generated array with shape `(4,6)`. Print this array. 

In [17]:
np.random.seed(1)
X = np.random.choice(range(10), 24).reshape(4,6)


Print the sum of all of the elements in `X`. 

In [18]:
print(np.sum(a = X))
print(X)

110
[[5 8 9 5 0 0]
 [1 7 6 9 2 4]
 [5 2 4 2 4 7]
 [7 9 1 7 0 6]]


Print an array containing the sums of the rows of `X`.

In [19]:
print(np.sum(a = X, axis = 1))

[27 29 24 30]


Print an array containing the sums of the columns of `X`.

In [20]:
print(np.sum(a = X, axis = 0))

[18 26 20 23  6 17]
